# Generated by Django 4.0.1 on 2022-06-04 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsstory',
            name='image',
            field=models.CharField(default='https://pixabay.com/images/id-1489825/', max_length=200),
        ),
    ]
