# Generated by Django 4.0.1 on 2022-06-04 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_newsstory_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsstory',
            name='image',
        ),
        migrations.AddField(
            model_name='newsstory',
            name='image_url',
            field=models.CharField(default='https://pixabay.com/images/id-1489825/', max_length=300),
        ),
    ]
